name: persist_http
description: "This library provides an efficient way to handle HTTP requests by reusing the same HTTP handshake. It's designed for Dart environments and supports all platforms except Flutter Web due to the use of dart:io."
version: 0.0.1-beta
homepage: https://github.com/JAYDARANIYA/persist_http
repository: https://github.com/JAYDARANIYA/persist_http
issue_tracker: https://github.com/JAYDARANIYA/persist_http/issues

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
